version: '3.8'
services:
  db:
    image: postgres:15
    container_name: board_games_db
    restart: always
    env_file:
      - .env  # <--- Докер сам прочитает переменные из этого файла
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
