version: '3.8'

services:
  db:
    image: postgres:15
    container_name: board_games_db
    restart: always
    env_file:
      - .env
    networks:
      - proxy_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    # Заменили 'build: .' на готовый образ. 
    # Теперь сервер просто скачает его, а не будет мучиться со сборкой.
    image: gennadypol/board-games-backend:latest
    container_name: board_games_backend
    restart: always
    env_file:
      - .env
    networks:
      - proxy_network
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    container_name: board_games_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - proxy_network
    depends_on:
      - backend

volumes:
  postgres_data:

networks:
  proxy_network:
    external: true
