"""add_index_to_game_datetime

Revision ID: 664f03334f84
Revises: 82bd61ba22a8
Create Date: 2026-03-24 00:24:52.388969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '664f03334f84'
down_revision: Union[str, Sequence[str], None] = '82bd61ba22a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_game_user_uc', 'bookings', ['game_id', 'user_id'])
    op.create_index(op.f('ix_games_date_time'), 'games', ['date_time'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_date_time'), table_name='games')
    op.drop_constraint('_game_user_uc', 'bookings', type_='unique')
    # ### end Alembic commands ###
