"""add creator_id to games

Revision ID: 82bd61ba22a8
Revises: 048e6aae7cc6
Create Date: 2026-03-22 19:19:31.305428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bd61ba22a8'
down_revision: Union[str, Sequence[str], None] = '048e6aae7cc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'creator_id')
    # ### end Alembic commands ###
