          script: |
            cd ~/my_app/backend-project
            git pull origin main
            echo "${{ secrets.ENV_FILE_BACKEND }}" > .env
            
            # Запускаем только то, что описано в ЭТОМ docker-compose.yml
            # (База, Бэкенд и Nginx)
            docker compose up -d --build
